### ISSUE TITLE
[Frontend] Login

### ISSUE THREAD

**Issue by jkairoy** [FullStackAtBrownTeam/project-first-at-brown#32]
- [x] Login page styling @TaishiNishizawa 
- [x] Login page functionality (API request) @tanjoshua

**Comment by tanjoshua** [comment]
Tried to use it but encountered some errors (https://github.com/react-native-google-signin/google-signin/issues/822). According to the package, there are some configurations that have to be done natively and I'm not sure if it is possible. Instead, I've instead opted to use expo-google-app-auth and I haven't encountered any major issues so far.

If you know how to solve those problems above or if I was setting it up wrongly, I can go back to the package you recommended though.

**Comment by jkairoy** [comment]
Sounds good 👍
